export const SIMULATION_WORKBENCH = {
  id: 'SIMULATION',
  label: 'Simulation',
  featureTypes: [
    'D',
    'P',
    'P.CU',
    'P.CY',
    'P.CO',
    'P.S',
    'P.T',
    'P.PY',
    'S',
    'E',
    'R',
    'SW',
    'TU',
    'B',
    'F',
    'CH',
    'H',
    'PF',
    'PATLIN',
    'PATRAD',
    'PATTERN',
    'XFORM',
    'M',
    'TEXT',
    'HX',
    'SP',
    'IMPORT3D',
    'IMAGE',
    'HEIGHTMAP',
  ],
  contextFamilies: {
    features: false,
    assemblyConstraints: false,
    pmiAnnotations: false,
  },
  sidePanels: {
    assemblyConstraints: false,
    pmiViews: true,
  },
  toolbarButtons: [
    'home',
    'new',
    'save',
    'zoomToFit',
    'wireframe',
    'import',
    'export',
    'share',
    'sheetEditor',
    'about',
    'historyTestSnippet',
    'scriptRunner',
    'undo',
    'redo',
    'tests',
    'selectionState',
  ],
};
